### ISSUE TITLE
Use Acme Test server?

### ISSUE THREAD

**Issue by p4tin** [dkumor/acmewrapper#12]
During my trial and error of using AcmeWrapper I hit the Let's Encrypt Rate Limit - is there a way to use Acme Wrapper with the let's encrypt test servers?

Great Project - keep it up!!

**Comment by dkumor** [comment]
Certainly! The configuration object accepts a "Server" parameter:
https://godoc.org/github.com/dkumor/acmewrapper#Config

This is an ACME server to use. You can set this to the staging server's URL, as is done in the tests:

https://github.com/dkumor/acmewrapper/blob/master/acme_test.go#L13

In this case, the server to use is `"https://acme-staging.api.letsencrypt.org/directory"`.

As a side note, there is now an "official" Let's Encrypt client: https://godoc.org/golang.org/x/crypto/acme/autocert
I am committed to maintaining ACMEWrapper, since my own projects use it, but in the long term I am guessing the community will standardize on `autocert`.

**Comment by p4tin** [comment]
Thanks!
