### ISSUE TITLE
Optional save load file hooks

### ISSUE THREAD

**Issue by jpillora** [dkumor/acmewrapper#2]
``` go
{
    // == In addition to:
    TLSCertFile: "cert.pem",
    TLSKeyFile:  "key.pem",
    // Let's Encrypt stuff
    RegistrationFile: "user.reg",
    PrivateKeyFile:   "user.pem",
    // == We could add two methods:
    SaveFileCallback: func(path, contents []byte) error {},
    LoadFileCallback: func(path string) (contents []byte, err error) {},
}
```
When provided, `acmewrapper` would use these instead of reading/writing to disk. For example, this could allow use of a shared key server over SSH.

Great project btw, was thinking of writing exactly this last week. Glad you beat me to it :)

**Comment by jpillora** [comment]
I can do the change if you like, just wanted to see if you we're okay with the API

**Comment by dkumor** [comment]
I'd love to incorporate a PR for something like that. 

I am guessing that the goal here is to be able to use your own database for storage of keys/certs and user registration. Is that right?

Ideally, the content would be in bytes, since that is the format certificates are kept in.

When writing certificates to disk, the library also saves the old certs/key as a backup with `.bak` extension. If these functions are passed, I am guessing that we would leave backups to the user. What do you suggest?

Finally, what do you think of adding a special error, such as `ErrNotHandled` as a return value to allow only handling a subset of the files, such that the library would read/write them to disk normally.. An example would be:

```go
func MySaveFile(path string, contents []byte) error {
    if path != "my_cert_file" {
        return acmewrapper.ErrNotHandled
    }
    // do your stuff
}
```

**Comment by jpillora** [comment]
Yep, when the functions are provided, user would handle all files. In a docker example where the container is ephemeral and has no mounted volumes (`docker run --rm ubuntu`) it wouldn't make sense to write anything ACME related to disk so I think it should cover backups too.

Awesome, I'll give this a shot some time today and `acmewrapper.ErrNotHandled` is a good idea, will implement that too.

**Comment by dkumor** [comment]
Sounds great! It looks like a pretty important feature for many use cases.
